from selenium.webdriver.common.by import By

class MainPageLocators(object):
    Continue_Button = (By.XPATH, '//*[@id="content"]/section[2]/div/div/a')

class DetailsPageLocators(object):
    Pet_Name = (By.XPATH, '//*[@id="yourDetailsPolicyHolderPetName0"]')
    Pet_Type = (By.XPATH, '//*[@id="dog0"]')
    Pet_Breed_Pedigree = (By.XPATH, '//*[@id="dogPedigree0"]')
    Pet_Breed_Cross = (By.XPATH, '//*[@id="dogCrossBreed0"]')
    Pet_Breed_Mixed = (By.XPATH, '//*[@id="breedSelector0"]/fieldset/div[2]/label[3]')
    Pet_Breed_Name = (By.XPATH, '//*[@id="predictiveTextBreedSelector0"]')
    Pet_Gender_Male = (By.XPATH, '/html/body/div[4]/div/section[3]/section/form/div[2]/div[1]/div[2]/div[1]/div/div/div/div[5]/fieldset/div/label[1]')
    Pet_Gender_Female = (By.XPATH, '/html/body/div[4]/div/section[3]/section/form/div[2]/div[1]/div[2]/div[1]/div/div/div/div[5]/fieldset/div/label[2]')
    Pet_DoB_Day = (By.XPATH, '//*[@id="pet0day"]')
    Pet_DoB_Month = (By.XPATH, '//*[@id="pet0month"]')
    Pet_DoB_Year = (By.XPATH, '//*[@id="pet0year"]')
    Pet_Price = (By.XPATH, '//*[@id="pay0"]')
    Pet_Nothing_Paid = (By.XPATH, '//*[@id="petCostDiv"]/div[3]/span[1]')
    Pet_N_or_S_Yes = (By.XPATH, '//*[@id="about-your-pet-body"]/div[8]/fieldset/div/label[1]')
    Pet_N_or_S_No = (By.XPATH, '//*[@id="about-your-pet-body"]/div[8]/fieldset/div/label[2]')
    Pet_N_or_S_Unsure = (By.XPATH, '//*[@id="about-your-pet-body"]/div[8]/fieldset/div/label[3]')
    Pet_Chipped_Yes = (By.XPATH, '//*[@id="chipped-or-tagged0"]/fieldset/div/label[1]')
    Pet_Chipped_No = (By.XPATH, '//*[@id="chipped-or-tagged0"]/fieldset/div/label[2]')
    Pet_Chipped_Unsure = (By.XPATH, '//*[@id="chipped-or-tagged0"]/fieldset/div/label[3]')
    Pet_Legal_Action_Yes = (By.XPATH, '//*[@id="legalActionTrue0"]')
    Pet_Legal_Action_No = (By.XPATH, '//*[@id="legalActionFalse0"]')
    Pet_Complaints_Yes = (By.XPATH, '//*[@id="complaintMadeTrue0"]')
    Pet_Complaints_No = (By.XPATH, '//*[@id="complaintMadeFalse0"]')
    Pet_Home_Yes = (By.XPATH, '//*[@id="about-your-pet-body"]/div[11]/fieldset/div/label[1]')
    Pet_Home_No = (By.XPATH, '//*[@id="about-your-pet-body"]/div[11]/fieldset/div/label[2]')
    Pet_Good_Health = (By.XPATH, '//*[@id="about-your-pet-body"]/div[12]/fieldset/div/label[1]')
    Pet_Bad_Heath = (By.XPATH, '//*[@id="about-your-pet-body"]/div[12]/fieldset/div/label[2]')
    Pet_Second_Pet_Close = (By.XPATH, '//*[@id="div_petDetails_pets1"]/div/div/button/div[1]')

class AboutYouLocators(object):
    Owner_Title = (By.XPATH, '//*[@id="yourDetailsPolicyHolderTitleSelectBoxIt"]')
    Owner_FirstName = (By.XPATH, '//*[@id="yourDetailsPolicyHolderFirstName"]')
    Owner_Surname = (By.XPATH, '//*[@id="yourDetailsPolicyHolderLastName"]')
    Owner_DoB_Day = (By.XPATH, '//*[@id="yourDetailsPolicyHolderDateOfBirthD"]')
    Owner_DoB_Month = (By.XPATH, '//*[@id="yourDetailsPolicyHolderDateOfBirthM"]')
    Owner_DoB_Year = (By.XPATH, '//*[@id="yourDetailsPolicyHolderDateOfBirthY"]')
    Owner_EmailAddress = (By.XPATH, '//*[@id="yourDetailsPolicyHolderEmailAddress"]')
    Owner_Phone_Number = (By.XPATH, '//*[@id="yourDetailsTelephone"]')
    Owner_Marital_Status = (By.XPATH, '//*[@id="marital-statusSelectBoxIt"]')
    Owner_Postcode = (By.XPATH, '//*[@id="yourDetailsPolicyHolderPostcode"]')
    Owner_FindAddress = (By.XPATH, '//*[@id="btn-find-address"]')
    Owner_EnterAddress = (By.XPATH, '//*[@id="yourDetailsAddressIncorrectButton"]')
    Owner_ManualPostcode = (By.XPATH, '//*[@id="yourDetailsManualAddressPostCode"]')
    Owner_HouseNumber = (By.XPATH, '//*[@id="yourDetailsManualAddressHouseNumber"]')
    Owner_Street = (By.XPATH, '//*[@id="yourDetailsManualAddressStreet"]')
    Owner_Town = (By.XPATH, '//*[@id="yourDetailsManualAddressTown"]')
    Owner_County = (By.XPATH, '//*[@id="yourDetailsManualAddressCountrySelectBoxItText"]')
    Owner_County_Kent = (By.XPATH, '/html/body/div[4]/div/section[3]/section/form/div[2]/div[1]/div[3]/div/'
                                   'div/div/div[9]/div[2]/div[6]/fieldset/div/span/ul/li[112]')
    Owner_1_Pet = (By.XPATH, '//*[@id="petsInHouseHoldAnchor"]/fieldset/div/label[1]')
    Owner_2_Pet = (By.XPATH, '//*[@id="petsInHouseHoldAnchor"]/fieldset/div/label[2]')
    Owner_3_Pet = (By.XPATH, '//*[@id="petsInHouseHoldAnchor"]/fieldset/div/label[3]')
    Owner_4_Pet = (By.XPATH, '//*[@id="petsInHouseHoldAnchor"]/fieldset/div/label[4]')
    Owner_5_Pet = (By.XPATH, '//*[@id="petsInHouseHoldAnchor"]/fieldset/div/label[5]')
    Owner_Informed_No = (By.XPATH, '//*[@id="marketing-n-label"]')
    Owner_Get_Quote = (By.XPATH, '//*[@id="submitForm"]')

class QuotePageLocators(object):
    Quote_Add_Another_Pet = (By.XPATH,'//*[@id="yourQuoteHide1"]/div[1]/div')
    Quote_Accident_Only = (By.XPATH, '//*[@id="iddEnhancedTile"]/div[3]/div[1]/fieldset/div/label[1]')
    Quote_AO_Monthly = (By.XPATH, '//*[@id="totalPriceText"]/span')
    Quote_AO_Yearly = (By.XPATH, '//*[@id="paymentPricePanel"]/div/div/p[1]/span')
    Quote_AO_Excess = (By.XPATH, '//*[@id="quote"]/div/label[2]')
    Quote_Accident_and_Illness = (By.XPATH, '//*[@id="iddEnhancedTile"]/div[3]/div[1]/fieldset/div/label[2]')
    Quote_AI_ShortTermOnly = (By.XPATH, '//*[@id="iddEnhancedTile"]/div[3]/div[2]/fieldset/div/label[1]')
    Quote_AI_Ongoing = (By.XPATH, '//*[@id="iddEnhancedTile"]/div[3]/div[2]/fieldset/div/label[2]')
    Quote_AI_ShortTermOnly_Monthly = (By.XPATH, '//*[@id="totalPriceText"]/span')
    Quote_AI_ShortTermOnly_Yearly = (By.XPATH, '//*[@id="paymentPricePanel"]/div/div/p[1]/span')
    Quote_AI_Ongoing_Extra_Monthly = (By.XPATH, '//*[@id="whatYouPaySectionTile"]/div[3]/div[3]/table/tbody/tr[1]/td[2]')
    Quote_AI_Ongoing_Extra_Yearly = (By.XPATH, '//*[@id="whatYouPaySectionTile"]/div[3]/div[3]/table/tbody/tr[2]/td[2]')
    Quote_AI_Ongoing_Premier_Monthly = (By.XPATH, '//*[@id="whatYouPaySectionTile"]/div[3]/div[4]/table/tbody/tr[1]/td[2]')
    Quote_AI_Ongoing_Premier_Yearly = (By.XPATH, '//*[@id="whatYouPaySectionTile"]/div[3]/div[4]/table/tbody/tr[2]/td[2]')

class AnimalFriendsAnimalType(object):
    Pet_Cat = (By.XPATH, '//*[@id="details-section"]/div[1]/div[1]/div/label[2]')
    Pet_Dog = (By.XPATH, '//*[@id="details-section"]/div[1]/div[1]/div/label[1]')

class AF_PreExistingCons(object):
    PreConNo = (By.XPATH, '//*[@id="details-section"]/div[2]/div/div[2]/div[1]/div/label[1]')
    PreConYes = (By.XPATH, '/html/body/div[5]/main/div[1]/div[1]/div[2]/div/div[2]/div[1]/div/label[2]')

class AF_Details(object):
    Pet_Name = (By.XPATH, '//*[@id="Name"]')
    Pet_Gender_Male = (By.XPATH, '//*[@id="pet-details"]/div[3]/div[1]/div/label[1]')
    Pet_Gender_Female = (By.XPATH, '//*[@id="pet-details"]/div[3]/div[1]/div/label[2]')
    Pet_DoB = (By.XPATH, '//*[@id="Dob"]')
    Pet_Breed_Mixed = (By.XPATH, 'html/body/div[5]/main/div/div/div[3]/div/form/div[7]/div/div/label[2]')
    Pet_Breed_Small = (By.XPATH, 'html/body/div[5]/main/div/div/div[3]/div/form/div[10]/div/div/label[1]')
    Pet_Breed_Medium = (By.XPATH, 'html/body/div[5]/main/div/div/div[3]/div/form/div[10]/div/div/label[2]')
    Pet_Breed_Large = (By.XPATH, 'html/body/div[5]/main/div/div/div[3]/div/form/div[10]/div/div/label[3]')
    Pet_Breed_Mog = (By.XPATH, '//*[@id="pet-details"]/div[6]/div[1]/div/label[1]')
    Pet_Breed_Cross = (By.XPATH, '//*[@id="pet-details"]/div[6]/div[1]/div/label[2]')
    Pet_Breed_Pedigree = (By.XPATH, 'html/body/div[5]/main/div/div/div[3]/div/form/div[7]/div/div/label[3]')
    Cat_Breed_Pedigree = (By.XPATH, '/html/body/div[5]/main/div[1]/div[1]/div[3]/div/form[1]/div[6]/div[1]/div/label[3]')
    Pet_Breed_Selection = (By.XPATH, 'html/body/div[5]/main/div/div/div[3]/div/form/div[8]/div/div/input')
    Cat_Breed_Selection = (By.XPATH, '/html/body/div[5]/main/div[1]/div[1]/div[3]/div/form[1]/div[7]/div[1]/div/input')
    Pet_PaidForYes = (By.XPATH, '//*[@id="pet-details"]/div[9]/div[1]/div/label[1]')
    Pet_Price = (By.XPATH, '//*[@id="Cost"]')
    Cat_Free = (By.XPATH, '/html/body/div[5]/main/div[1]/div[1]/div[3]/div/form[1]/div[9]/div[1]/div/label[2]')
    Cat_Paid_Btn = (By.XPATH, '//*[@id="pet-details"]/div[9]/div[1]/div/label[1]')
    Mix_Paid_Btn = (By.XPATH, '//*[@id="pet-details"]/div[12]/div[1]/div/label[1]')
    Dog_Paid_Btn = (By.XPATH, '//*[@id="pet-details"]/div[10]/div[1]/div/label[1]')
    Mix_Free = (By.XPATH, '/html/body/div[5]/main/div[1]/div[1]/div[3]/div/form[1]/div[12]/div[1]/div/label[2]')
    Pet_Free = (By.XPATH, '/html/body/div[5]/main/div[1]/div[1]/div[3]/div/form[1]/div[10]/div[1]/div/label[2]')
    Mix_Paid_txt = (By.XPATH, '//*[@id="Cost"]')
    Dog_Paid_txt = (By.XPATH, '//*[@id="Cost"]')
    Cat_Paid_txt = (By.XPATH, '//*[@id="pet-details"]/div[10]/div[1]/div/label')
    Pet_PriorInsured = (By.XPATH, '//*[@id="pet-details"]/div[11]/div/div[2]/div/label[1]')
    Pet_NeverInsured = (By.XPATH, '/html/body/div[5]/main/div[1]/div[1]/div[3]/div/form[1]/div[12]/div/div[2]/div/label[2]')
    Cat_NeverInsured = (By.XPATH, '/html/body/div[5]/main/div[1]/div[1]/div[3]/div/form[1]/div[11]/div/div[2]/div/label[2]')
    Mix_NeverInsured = (By.XPATH, '/html/body/div[5]/main/div[1]/div[1]/div[3]/div/form[1]/div[14]/div/div[2]/div/label[2]')
    Pet_AccidentYes = (By.XPATH, '//*[@id="pet-details"]/div[11]/div/div[6]/div/label[1]')
    Pet_AccidentNo = (By.XPATH, '/html/body/div[5]/main/div[1]/div[1]/div[3]/div/form[1]/div[12]/div/div[6]/div/label[2]')
    Mix_AccidentNo = (By.XPATH, '/html/body/div[5]/main/div[1]/div[1]/div[3]/div/form[1]/div[14]/div/div[2]/div/label[2]')
    Cat_AccidentNo = (By.XPATH, '/html/body/div[5]/main/div[1]/div[1]/div[3]/div/form[1]/div[11]/div/div[6]/div/label[2]')
    Pet_DeclinedInsurance = (By.XPATH, '//*[@id="pet-details"]/div[11]/div/div[9]/div/label[1]')
    Pet_NotDeclinedInsurance = (By.XPATH, '/html/body/div[5]/main/div[1]/div[1]/div[3]/div/form[1]/div[12]/div/div[9]/div/label[2]')
    Cat_NotDeclinedInsurance = (By.XPATH, '/html/body/div[5]/main/div[1]/div[1]/div[3]/div/form[1]/div[11]/div/div[9]/div/label[2]')
    Mix_NotDeclinedInsurance = (By.XPATH, '/html/body/div[5]/main/div[1]/div[1]/div[3]/div/form[1]/div[14]/div/div[9]/div/label[2]')
    Pet_CoverDate = (By.XPATH, '//*[@id="InceptionDate"]')
    Owner_Title = (By.XPATH, '//*[@id="client-details"]/div[1]/div[1]/div/div/input')
    Owner_FirstName = (By.XPATH, '//*[@id="ClientName"]')
    Owner_LastName = (By.XPATH, '//*[@id="ClientSurname"]')
    Owner_Email = (By.XPATH, '//*[@id="ClientEmail"]')
    Owner_Phone = (By.XPATH, '//*[@id="ClientPhone"]')
    Owner_DoB = (By.XPATH, '//*[@id="ClientDob"]')
    Owner_ManualAddressBtn = (By.XPATH, '//*[@id="client-details"]/div[5]/div[3]/span[2]')
    Owner_Address_1 = (By.XPATH, '//*[@id="ManualHouseName"]')
    Owner_Address_2 = (By.XPATH, '//*[@id="ManualStreet"]')
    Owner_Town = (By.XPATH, '//*[@id="ManualTownOrCity"]')
    Owner_County = (By.XPATH, '//*[@id="ManualCounty"]')
    Owner_Postcode = (By.XPATH, '//*[@id="ManualPostcode"]')
    Owner_FindUs = (By.XPATH, '//*[@id="client-details"]/div[8]/div[1]/div/div/input')
    ContinueButton = (By.XPATH, '//*[@id="details-section"]/div[4]/button')

class AF_QuoteType(object):
    AccidentOnly = (By.XPATH, '//*[@id="quote-section-content"]/div[2]/div/div/div[1]/div[3]/div[1]/div/label[1]')
    AccidentAndIllness = (By.XPATH, '//*[@id="quote-section-content"]/div[2]/div/div/div[1]/div[3]/div[1]/div/label[2]')
    AccidentMonthlyPrice = (By.XPATH, '//*[@id="quote-section-content"]/div[4]/div/div[8]/div[1]/div[1]/div[2]/span[1]')
    AccidentYearlyPrice = (By.XPATH, '//*[@id="quote-section-content"]/div[4]/div/div[8]/div[1]/div[1]/div[3]')
    AccidentSelectPolicy = (By.XPATH, '//*[@id="select-pet-cover-accident"]')
    AI_ShortTermButton = (By.XPATH, '//*[@id="quote-section-content"]/div[2]/div/div/div[2]/div[3]/div[1]/div/label[1]')
    AI_ConditionLimitButton = (By.XPATH, '//*[@id="quote-section-content"]/div[2]/div/div/div[2]/div[3]/div[1]/div/label[2]')
    AI_LongTerm = (By.XPATH, '//*[@id="quote-section-content"]/div[2]/div/div/div[2]/div[3]/div[1]/div/label[3]')
    AI_1000_Button = (By.XPATH, '//*[@id="quote-section-content"]/div[2]/div/div/div[3]/div[3]/div[1]/div/label[1]')
    AI_2000_Button = (By.XPATH, '//*[@id="quote-section-content"]/div[2]/div/div/div[3]/div[3]/div[1]/div/label[2]')
    AI_ST_1000_TopMonthly = (By.XPATH, '//*[@id="quote-section-content"]/div[4]/div/div[2]/div[1]/div[1]/div[2]/span[1]')
    AI_ST_1000_TopYearly = (By.XPATH, '//*[@id="quote-section-content"]/div[4]/div/div[2]/div[1]/div[1]/div[3]')
    AI_ST_2000_TopMonthly = (By.XPATH, '//*[@id="quote-section-content"]/div[4]/div/div[5]/div[1]/div[1]/div[2]/span[1]')
    AI_ST_2000_TopYearly = (By.XPATH, '//*[@id="quote-section-content"]/div[4]/div/div[5]/div[1]/div[1]/div[3]')
    AI_ConditionLimit_1000_TopMonthly = (By.XPATH, '//*[@id="quote-section-content"]/div[4]/div/div[3]/div[1]/div[1]/div[2]/span[1]')
    AI_ConditionLimit_1000_TopYearly = (By.XPATH, '//*[@id="quote-section-content"]/div[4]/div/div[3]/div[1]/div[1]/div[3]')
    AI_ConditionLimit_2000_TopMonthly = (By.XPATH, '//*[@id="quote-section-content"]/div[4]/div/div[6]/div[1]/div[1]/div[2]/span[1]')
    AI_ConditionLimit_2000_TopYearly = (By.XPATH, '//*[@id="quote-section-content"]/div[4]/div/div[6]/div[1]/div[1]/div[3]')
    AI_LT_1000_VetExcess = (By.XPATH, '//*[@id="quote-section-content"]/div[4]/div/div[4]/div[1]/div[6]/div[2]')
    AI_LT_1000_TopMonthly = (By.XPATH, '//*[@id="quote-section-content"]/div[4]/div/div[4]/div[1]/div[1]/div[2]/span[1]')
    AI_LT_1000_TopYearly = (By.XPATH, '//*[@id="quote-section-content"]/div[4]/div/div[4]/div[1]/div[1]/div[3]')
    AI_LT_2000_VetExcess = (By.XPATH, '//*[@id="quote-section-content"]/div[4]/div/div[7]/div[1]/div[6]/div[2]')
    AI_LT_2000_TopMonthly = (By.XPATH, '//*[@id="quote-section-content"]/div[4]/div/div[7]/div[1]/div[1]/div[2]/span[1]')
    AI_LT_2000_TopYearly = (By.XPATH, '//*[@id="quote-section-content"]/div[4]/div/div[7]/div[1]/div[1]/div[3]')
    AI_LT_4000_VetExcess = (By.XPATH, '//*[@id="quote-section-content"]/div[4]/div/div[11]/div[1]/div[6]/div[2]')
    AI_LT_4000_TopMonthly = (By.XPATH, '//*[@id="quote-section-content"]/div[4]/div/div[11]/div[1]/div[1]/div[2]/span[1]')
    AI_LT_4000_TopYearly = (By.XPATH, '//*[@id="quote-section-content"]/div[4]/div/div[11]/div[1]/div[1]/div[3]')
    AI_LT_6000_VetExcess = (By.XPATH, '//*[@id="quote-section-content"]/div[4]/div/div[12]/div[1]/div[6]/div[2]')
    AI_LT_6000_TopMonthly = (By.XPATH, '//*[@id="quote-section-content"]/div[4]/div/div[12]/div[1]/div[1]/div[2]/span[1]')
    AI_LT_6000_TopYearly = (By.XPATH, '//*[@id="quote-section-content"]/div[4]/div/div[12]/div[1]/div[1]/div[3]')


class PetPlan_PetDetails(object):
    btn_Dog = (By.XPATH, '//*[@id="petTypeDogLabel[0]"]')
    txt_PetName = (By.XPATH, '//*[@id="name[0]"]')
    btn_Male = (By.XPATH, '//*[@id="MaleLabel[0]"]')
    btn_Female = (By.XPATH, '//*[@id="FemaleLabel[0]"]')
    btn_Neutered_Yes = (By.XPATH, '/html/body/main/div[1]/div/div/div/div/form/div/ng-form/div[2]/div/section/div[3]/div[3]/label/span')
    btn_Neutered_No = (By.XPATH, '/html/body/main/div[1]/div/div/div/div/form/div/ng-form/div[2]/div/section/div[3]/div[4]/label/span')
    btn_PreviouslyInjured_No = (By.XPATH, '/html/body/main/div[1]/div/div/div/div/form/div/ng-form/div[2]/div/section/div[4]/div[3]/label/span')
    btn_Dog_Pedigree = (By.XPATH, '//*[@id="PedigreeLabel[0]"]')
    btn_Dog_Cross = (By.XPATH, '//*[@id="CrossbreedLabel[0]"]')
    btn_Dog_Mixed = (By.XPATH, '//*[@id="MixedbreedLabel[0]"]')
    txt_Dog_Breed = (By.XPATH, '//*[@id="pedigreeBreed[0]"]')
    Select_Day = (By.XPATH, '//*[@id="dateOfBirth[0]relday"]')
    Select_Month = (By.XPATH, '//*[@id="dateOfBirth[0]relmonth"]')
    Select_Year = (By.XPATH, '//*[@id="dateOfBirth[0]relyear"]')
    check_Dog_Behaviour = (By.XPATH, '//*[@id="behaviourLabel[0]"]')
    check_Dog_Attack = (By.XPATH, '//*[@id="hasAttackedLabel[0]"]')
    check_Dog_Guard = (By.XPATH, '//*[@id="isGuardDogLabel[0]"]')
    check_Dog_Alcohol = (By.XPATH, '//*[@id="livesWithAlcoholLabel[0]"]')
    check_Dog_NoWork = (By.XPATH, '//*[@id="takenToWorkLabel[0]"]')
    btn_Dog_Continue = (By.XPATH, '/html/body/main/div[1]/div/div/div/div/form/section[2]/div[2]/div[3]/span/span/span/span/button')
    btn_Cat = (By.XPATH, '//*[@id="petTypeCatLabel[0]"]')
    txt_Cat_Breed = (By.XPATH, '//*[@id="breed[0]"]')
    btn_Dog_Mixed_Small = (By.XPATH, '//*[@id="SmallLabel[0]"]')
    btn_Dog_Mixed_Medium = (By.XPATH, '//*[@id="MediumLabel[0]"]')
    btn_Dog_Mixed_Large = (By.XPATH, '//*[@id="LargeLabel[0]"]')

class PetPlan_OwnerDetails(object):
    Select_Title = (By.XPATH, '//*[@id="title"]')
    txt_FirstName = (By.XPATH, '//*[@id="firstName"]')
    txt_Surname = (By.XPATH, '//*[@id="lastName"]')
    Select_Day = (By.XPATH, '//*[@id="dateOfBirth[]relday"]')
    Select_Month = (By.XPATH, '//*[@id="dateOfBirth[]relmonth"]')
    Select_Year = (By.XPATH, '//*[@id="dateOfBirth[]relyear"]')
    txt_PhoneNumber = (By.XPATH, '//*[@id="contactNumber"]')
    txt_Email = (By.XPATH, '//*[@id="email"]')
    txt_Postcode = (By.XPATH, '//*[@id="postCode"]')
    btn_FindAddress = (By.XPATH, '//*[@id="findAddressBtn"]/div/div')
    Select_Address = (By.XPATH, '//*[@id="addressList"]')
    btn_OwnerContinue = (By.XPATH, '//*[@id="skipnav"]/div[1]/div/div/div/div/form/section[3]/div/div[3]/button')
    txt_HouseNumber = (By.XPATH, '//*[@id="houseNameOrNumber"]')
    txt_Street = (By.XPATH, '//*[@id="street"]')
    txt_Town = (By.XPATH, '//*[@id="town"]')
    txt_County = (By.XPATH, '//*[@id="county"]')

class PetPlan_Quote(object):
    btn_Ongoing = (By.XPATH, '//*[@id="coveredForLifeBtn"]')
    txt_NoCover = (By.XPATH, '//*[@id="selectProduct"]/section/div[2]/div[3]/div/div/p/text()[1]')
    out_4000_Month = (By.XPATH, '//*[@id="selectProduct"]/section[2]/div[2]/div/div[1]/div/div[1]/h3')
    out_4000_Annual = (By.XPATH, '//*[@id="selectProduct"]/section[2]/div[2]/div/div[1]/div/div[1]/p')
    out_4000_VetFees = (By.XPATH, '/html/body/main/div[1]/div/div/div/div/div[2]/div/div/section/div/ng-include/form/section[2]/div[2]/div/div[4]/div/div/div[1]/span[1]')
    out_7000_Month = (By.XPATH, '//*[@id="selectProduct"]/section[2]/div[2]/div/div[1]/div/div[2]/h3')
    out_7000_Annual = (By.XPATH, '//*[@id="selectProduct"]/section[2]/div[2]/div/div[1]/div/div[2]/p')
    out_7000_VetFees = (By.XPATH, '/html/body/main/div[1]/div/div/div/div/div[2]/div/div/section/div/ng-include/form/section[2]/div[2]/div/div[4]/div/div/div[2]/span[1]')
    out_12000_Month = (By.XPATH, '//*[@id="selectProduct"]/section[2]/div[2]/div/div[1]/div/div[3]/h3')
    out_12000_Annual = (By.XPATH, '//*[@id="selectProduct"]/section[2]/div[2]/div/div[1]/div/div[3]/p')
    out_12000_VetFees = (By.XPATH, '/html/body/main/div[1]/div/div/div/div/div[2]/div/div/section/div/ng-include/form/section[2]/div[2]/div/div[4]/div/div/div[3]/span[1]')
